ModelBindingAssignment/Models/ErrorViewModel.cs
namespace ModelBindingAssignment.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

ModelBindingAssignment/Models/Song.cs
using System.ComponentModel.DataAnnotations;
using System.Reflection.Metadata.Ecma335;

namespace ModelBindingAssignment.Models
{
	/// <summary>
	/// Represents one song
	/// </summary>
	public class Song
	{
		/// <summary>
		/// Song's title, or name
		/// </summary>
		[Required(ErrorMessage = "Song name can't be empty")]
		public string Name { get; set; }

		/// <summary>
		/// Album song was featured in. If the song was a single,
		/// "Single" should be the value for Album.
		/// </summary>
		[Required(ErrorMessage = "Song album can't be empty")]
		public string Album { get; set; }

		/// <summary>
		/// Name of the band or the artist that the song
		/// is credited to.
		/// </summary>
		[Required(ErrorMessage = "Song artist can't be empty")]
		public string Artist { get; set; }

		/// <summary>
		/// Length of the song in minutes. Rounded off to 2
		/// decimal places. Length can't be negative but can
		/// be 0 for cases when song length isn't known yet.
		/// Max value is 8400 or 140 hrs. Worlds longest song
		/// is 138 hours long. That's a real fact.
		/// </summary>
		[Range(0, 8400, ErrorMessage = "Length can't be under 0")]
		public double Length { get; set; }

	}
}

ModelBindingAssignment/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ModelBindingAssignment.Models;
using System.Diagnostics;

namespace ModelBindingAssignment.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

ModelBindingAssignment/Controllers/SongController.cs
using Microsoft.AspNetCore.Mvc;
using ModelBindingAssignment.Models;

namespace ModelBindingAssignment.Controllers
{
    public class SongController : Controller
    {
        [HttpGet]
        public IActionResult CreateSong()
        {
            return View();
        }
		[HttpPost]
		public IActionResult CreateSong(Song s)
		{
			if(ModelState.IsValid)
			{
				// Add valid song to database
				return RedirectToAction("CreateSong");
			}

			return View();
		}
	}
}

ModelBindingAssignment/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ModelBindingAssignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ModelBindingAssignment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ModelBindingAssignment.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ModelBindingAssignment</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Song" asp-action="CreateSong">Create a song</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ModelBindingAssignment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ModelBindingAssignment/Views/Song/CreateSong.cshtml
@model Song
@{
	ViewData["Title"] = "Create a song";
}

<h1> Create a song </h1>
<div class="container-md">
	<form method="post">
		<div>
			<label class="form-label" asp-for="Name">Song Name: </label>
			<input class="form-control" asp-for="Name" />
			<span class="text-warning" asp-validation-for="Name"></span>
		</div>
		
		<div>
			<label class="form-label" asp-for="Album">Album Name: </label>
			<input class="form-control" asp-for="Album" />
			<span class="text-warning" asp-validation-for="Album"></span>
		</div>
		
		<div>
			<label class="form-label" asp-for="Artist">Artist Name: </label>
			<input class="form-control" asp-for="Artist" />
			<span class="text-warning" asp-validation-for="Artist"></span>
		</div>
		
		<div>
			<label class="form-label" asp-for="Length">Song Length (minutes): </label>
			<input class="form-control" asp-for="Length" />
			<span class="text-warning" asp-validation-for="Length"></span>
		</div>
		
		<br />

		<input class="btn btn-outline-primary" type="submit" value="Create Song" />
	</form>
</div>